---
author:
  - 'Ævar Arnfjörð Bjarmason <avar@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.12'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Digest-Whirlpool
no_index:
  directory:
    - inc
    - t
requires:
  Digest: 0
  Digest::base: 0
  Getopt::Long: 0
  MIME::Base64: 0
  Pod::Usage: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Digest-Whirlpool
  homepage: http://metacpan.org/release/Digest-Whirlpool
  license: http://dev.perl.org/licenses/
  repository: git://github.com/avar/digest-whirlpool.git
version: 2.04
